spring.application.name=leadManagment

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lead_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Postgresql}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:MyVerySecretKeyForLeadManagementProject2026MyVerySecretKey123456}
jwt.expiration=${JWT_EXPIRATION:3600000}
logging.level.org.springframework.security=DEBUG

app.default-admin.username=${DEFAULT_ADMIN_USERNAME:admin}
app.default-admin.password=${DEFAULT_ADMIN_PASSWORD:admin123}

app.default-member.username=${DEFAULT_MEMBER_USERNAME:member}
app.default-member.password=${DEFAULT_MEMBER_PASSWORD:member123}